import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Oswald } from "next/font/google";
import "./globals.css";
import TopNavbar from "@/components/TopNavbar";
import BottomFooter from "@/components/BottomFooter";
import { ThemeInit } from "../.flowbite-react/init";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});
const oswald = Oswald({ subsets: ["latin"], variable: "--font-heading" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Juicy Burger!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, inter.variable, oswald.variable, "font-sans")}
    >
      <body className="min-h-full flex flex-col">
        <ThemeInit />
        <TopNavbar />
        {children}
        <BottomFooter />
        </body>
    </html>
  );
}
